# Generated by Django 3.0.2 on 2020-02-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
