# Generated by Django 3.0.2 on 2020-02-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20200202_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=20),
            preserve_default=False,
        ),
    ]
